# Generated by Django 2.2.10 on 2021-10-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField(verbose_name='date published')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question_choice', models.CharField(max_length=255)),
                ('votes', models.IntegerField(default=0)),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.Question')),
            ],
        ),
    ]
