# Generated by Django 2.2.10 on 2021-10-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0002_auto_20211023_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
